# Generated by Django 4.2.1 on 2023-05-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mememaker', '0004_meme_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='url',
        ),
    ]
