# Generated by Django 4.2.1 on 2023-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mememaker', '0005_remove_meme_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='url',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
