# Generated by Django 4.2.1 on 2023-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mememaker', '0006_meme_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
