# Generated by Django 4.2.1 on 2023-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mememaker', '0002_meme_url_meme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='url',
        ),
    ]
