# Generated by Django 4.2.1 on 2024-05-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mememaker", "0009_rename_id1_meme_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meme",
            old_name="id",
            new_name="id2",
        ),
    ]
