# Generated by Django 4.2.1 on 2024-05-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mememaker", "0011_rename_id2_meme_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meme",
            old_name="id",
            new_name="id1",
        ),
    ]
