# Generated by Django 4.2.1 on 2024-05-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mememaker", "0012_rename_id_meme_id1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meme",
            old_name="id1",
            new_name="id",
        ),
    ]
